### ISSUE TITLE
Is it possible to write log output into a file?

### ISSUE THREAD

**Issue by bricejlin** [ericelliott/bunyan-request-logger#12]
Trying to use it to analyze my logs

**Comment by ericelliott** [comment]
Sure, a couple of ways:

## Option one: Stream stdout to a file

This is the option I recommend because it's the most flexible, and doesn't conflate log management with the application's responsibilities -- IMO, what happens to the log is not the application's job. Redirect stdout to a log file. There are lots of tools for linux that can handle file management, rotation, aggregation (syslogd, etc...). How to wrangle OS-level I/O streams is outside the scope of this module.

## Option 2: Use Bunyan options
Or you can use [Bunyan's built-in file logging capabilities](https://github.com/trentm/node-bunyan#stream-type-rotating-file).

**Comment by bricejlin** [comment]
Got it. PM2 looks promising. Is it just doing option 1 for us? I see that it autogenerates the stdout logs into log files. And I guess a logparser like Logstash would read those files? Is that the workflow you would use with PM2 for logging?

**Comment by ericelliott** [comment]
Yes, PM2 is an automated version of Option 1. Logstash can be configured to read those files and aggregate to a central log database for analysis. That is how I would do it, yes.

**Comment by bricejlin** [comment]
Great! Thanks for the advice!
